### ISSUE TITLE
Error: Cannot find module '../server/dataSources'

### ISSUE THREAD

**Issue by me6iaton** [duffn/loopback-rethinkdb-example#1]
https://github.com/duffn/loopback-rethinkdb-example/blob/master/data/sampledata.js#L4
https://github.com/duffn/loopback-rethinkdb-example/blob/master/server/rethink-changes.js#L4
How i can connect dataSources.rethinkdb?

**Comment by duffn** [comment]
This works for me.

### Setup

`git clone https://github.com/duffn/loopback-rethinkdb-example.git`
`cd loopback-rethinkdb-example`
`npm install`

### Run the sample data script

`node data/sampledata.js`

### Run the real-time script

`node server/rethink-changes.js`
